apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpfoyer-17-deployment
  labels:
    app: tpfoyer-17
spec:
  replicas: 2  # Nombre de réplicas de votre application (peut être ajusté selon les besoins)
  selector:
    matchLabels:
      app: tpfoyer-17
  template:
    metadata:
      labels:
        app: tpfoyer-17
    spec:
      containers:
        - name: tpfoyer-17
          image: ichrakblk/tpfoyer-17:0.0.1  # L'image Docker à utiliser pour le déploiement
          ports:
            - containerPort: 8080  # Port d'écoute de votre application
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"  # Profile Spring (si nécessaire)
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
