version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db
      - innodb_force_recovery=1
    ports:
      - 3309:3309
    volumes:
      - db:/var/lib/mysql
  app-tpFoyer:
    depends_on:
      - mysqldb
    image: ichrakblk/tpfoyer-17:0.0.1
    #build : ./
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        spring.datasource.url=jdbc:mysql://localhost:3309/db?createDatabaseIfNotExist=true
        spring.datasource.username=root
        spring.datasource.password=
        spring.jpa.show-sql=true
        spring.jpa.hibernate.ddl-auto=update
        spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
      }'
    stdin_open: true
    tty: true

  frontend:
    depends_on:
      - app-tpFoyer
    image: ichrakblk/tpfoyer-17-frontend
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - VUE_APP_API_URL=http://app-tpFoyer:8082

volumes:
  db :