apiVersion: v1
kind: Service
metadata:
  name: tpfoyer-17-service
spec:
  selector:
    app: tpfoyer-17
  ports:
    - protocol: TCP
      port: 80        # Port exposé à l'extérieur du cluster
      targetPort: 8080 # Port de votre application à l'intérieur du cluster
  type: LoadBalancer  # Expose l'application à l'extérieur du cluster (si votre cluster supporte LoadBalancer)
