version: '3.8'

services:
  app:
    image: mon_image:latest
    container_name: mon_container_v2
    ports:
      - "8083:8082"
    environment:
      - SOME_ENV_VAR=value
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped