version: '3.8'

services:
  app:
    image: mon_image:latest
    container_name: mon_container_v2
    ports:
      - "8082:8080"
    environment:
      SOME_ENV_VAR: value  # Utilisez `:` au lieu de `=` pour définir les variables d'environnement
    restart: unless-stopped
